#!/usr/bin/env python3
"""Generate a symbol for every testbench, and the index that holds them.

xschem descends into a schematic when you select a symbol and press 'e'.  The
mechanism is nothing more than a naming convention: a symbol of
type=subcircuit called foo.sym descends into foo.sch in the same library
directory.  sky130A and gf180mcuD both build their test index this way -
sky130_tests/top.sch and tests/0_top.sch - and so does this one.

A test symbol carries no pins.  A testbench is self-contained: it has its own
sources and its own .control block, and nothing connects to it.  The symbol is
a rectangle and two labels, and it exists so that the index has something to
click on.

    python3 scripts/build_test_symbols.py

Writes libs.tech/xschem/tests/<name>.sym for every entry in TESTS, and
libs.tech/xschem/tests/0_top.sch.  Both are generated - do not hand-edit them,
edit TESTS below.  The '0_' prefix is gf180mcuD's trick to sort the index
first in the file browser.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
TESTS_DIR = os.path.join(ROOT, "libs.tech", "xschem", "tests")

# (schematic basename, column, label shown on the box)
#
# The column decides where the box lands in the index; the label is what it
# says.  The label is free text, so a schematic does not have to be renamed to
# read well on the index.
TESTS = [
    ("tft_iv",       "DEVICE",     "Output curves  Id-Vds"),
    ("tft_transfer", "DEVICE",     "Transfer curves  Id-Vgs"),
    ("tft_diode",    "DEVICE",     "Diode-connected TFT"),
    ("tft_cv",       "PARASITICS", "Gate capacitance  C-V"),
    ("tft_cv_estimated", "PARASITICS", "C-V with the semiconductor  (est.)"),
    ("tft_bfield",   "PHYSICS",    "Magnetic field"),
    ("tank_ac",      "CIRCUIT",    "LC tank  100 MHz"),
]

COLUMNS = ["DEVICE", "PARASITICS", "PHYSICS", "CIRCUIT"]

LICENCE = """* Copyright 2026 UCI/INRF - MMM Lab
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* GENERATED by scripts/build_test_symbols.py - do not edit by hand."""

# Box geometry, taken from gf180mcuD's test symbols so that the index looks
# like the one next door: 260 wide, 20 tall, centred on the origin.
HALF_W, HALF_H = 130, 10


def symbol(name, label):
    """One test symbol: a rectangle, the label, and the instance name.

    type=subcircuit is what enables descend.  @descr is substituted from the
    template, so the box can read 'Output curves Id-Vds' while the file is
    called tft_iv.sch - no renaming, and run_checks.sh keeps working.
    """
    # Roughly centre the label.  At xschem's 0.3 scale a character is about
    # six units wide, so half the string is 3*len to the left of the origin.
    # Close enough is close enough; nothing depends on it.
    x = -3.0 * len(label)
    return f"""v {{xschem version=3.4.5 file_version=1.2

{LICENCE}
}}
K {{type=subcircuit
format="@name @pinlist @symname"
template="name=x1 descr=\\"{label}\\""
}}
T {{@descr}} {x:g} -6 0 0 0.3 0.3 {{}}
T {{@name}} {HALF_W + 5} -22 0 0 0.2 0.2 {{}}
L 4 {-HALF_W} {-HALF_H} {HALF_W} {-HALF_H} {{}}
L 4 {-HALF_W} {HALF_H} {HALF_W} {HALF_H} {{}}
L 4 {-HALF_W} {-HALF_H} {-HALF_W} {HALF_H} {{}}
L 4 {HALF_W} {-HALF_H} {HALF_W} {HALF_H} {{}}
"""


def index():
    """0_top.sch - one clickable box per testbench, in columns by family."""
    # 260-wide boxes, 320 apart, so neighbouring columns clear each other.
    col_x = {c: 190 + 320 * i for i, c in enumerate(COLUMNS)}
    top_y = -640            # first box of every column
    step = 60
    head_y = top_y - 50     # column heading
    rule_top = top_y - 70   # vertical separators
    rule_bot = -80

    out = [f"""v {{xschem version=3.4.5 file_version=1.2

* The testbenches of the UCI/INRF IGZO TFT process (igzo_mmm_lab).
*
{LICENCE[LICENCE.index("* Licensed"):]}
}}
G {{}}
K {{}}
V {{}}
S {{}}
E {{}}"""]

    # column rules and headings
    for c in COLUMNS:
        x = col_x[c] - 150
        out.append(f"L 7 {x} {rule_top} {x} {rule_bot} {{}}")
        out.append(f"T {{{c}}} {x + 20} {head_y} 0 0 0.7 0.7 {{}}")
    last = col_x[COLUMNS[-1]] + 150
    out.append(f"L 7 {last} {rule_top} {last} {rule_bot} {{}}")

    out.append("T {The testbenches of the IGZO TFT process} 30 %d 0 0 0.8 0.8 "
               "{layer=8}" % (top_y - 200))
    out.append("T {Select a box with a mouse click, then press the 'e' key to "
               "descend into it.\nEach one is self-contained - its own models, "
               "its own sources, its own .control block - and prints what it "
               "measured.\nNetlisting THIS schematic is meaningless: it is an "
               "index, not a design.} 30 %d 0 0 0.4 0.4 {layer=11}"
               % (top_y - 160))

    n = 0
    for c in COLUMNS:
        y = top_y
        for name, col, _label in TESTS:
            if col != c:
                continue
            n += 1
            out.append(f"C {{tests/{name}.sym}} {col_x[c]} {y} 0 0 {{name=x{n}}}")
            y += step

    out.append('C {devices/title.sym} 160 -30 0 0 '
               '{name=l1 author="UCI/INRF - MMM Lab"}')
    out.append('C {devices/launcher.sym} 30 %d 0 0 {name=h1\n'
               'descr="TFT-MMM-LAB-PDK on GitHub"\n'
               'url="https://github.com/Juander28/TFT-MMM-LAB-PDK"}' % (top_y - 250))
    return "\n".join(out) + "\n"


def main():
    for name, _col, label in TESTS:
        sch = os.path.join(TESTS_DIR, name + ".sch")
        if not os.path.exists(sch):
            raise SystemExit(f"no schematic for {name}: {sch}")
        path = os.path.join(TESTS_DIR, name + ".sym")
        with open(path, "w") as f:
            f.write(symbol(name, label))
        print("wrote", os.path.relpath(path, ROOT))

    path = os.path.join(TESTS_DIR, "0_top.sch")
    with open(path, "w") as f:
        f.write(index())
    print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
